### ISSUE TITLE
Coordinate pre-production access for Gray to view APIs

### ISSUE THREAD

**Issue by gbinal** [18F/CMS.gov-developer#20]

**Comment by mraschka-CMS** [comment]
Two APIs will be our focus initially:

1) Tax Tools
CMS Product Owner - Greg Price
Contractor Project Manager - Mike Sutton (Aquilent)
Contractor Developer Lead - Greg Gershman (Ad Hoc)

2) Geography Service
CMS Product Owner - Vidit Majmudar
Contractor Developer Lead - James Connor

These APIs are pre-production and are currently in development now.

**Comment by gbinal** [comment]
We did this for the Geography service but weren't able to for the Tax Tools.
