### ISSUE TITLE
Enable api.data.gov testing 

### ISSUE THREAD

**Issue by gbinal** [18F/CMS.gov-developer#21]
- [x] CMS to send Gray who should get accounts 
- [x] Gray to create accounts and grant access
- [x] CMS to pick an endpoint they want to test

In support of #16

**Comment by nmudd-cms** [comment]
@gbinal, I just sent you a list of names for api.data.gov.

**Comment by gbinal** [comment]
Confirmed.  

@vidit-majmudar-cms - We need you to reply to the thread with an endpoint for us to add.

**Comment by vidit-majmudar-cms** [comment]
@gbinal - How about api.data.gov/hcgov/dev/marketplace? 

FYI: We are internally using second or third level sub-domains like marketplace.api.healthcare.gov(Non-prod: {dev/test/imp}.marketplace.api.healthcare.gov) in lieu of URL paths.

**Comment by gbinal** [comment]
The GEO API was eventually chosen instead and set up with api.data.gov.
