### ISSUE TITLE
Document an agile process to get through the ATO system. 

### ISSUE THREAD

**Issue by gbinal** [18F/CMS.gov-developer#29]
It would be in the format of "want to deliver quick agile software? Here how to blaze through the compliance process"

**Comment by gbinal** [comment]
Along the lines of:
- https://github.com/fisma-ready/fisma-ready.github.io
- https://github.com/fisma-ready

**Comment by mraschka-CMS** [comment]
Pull in members of our internal CMS AWS support group - contact via: AWS_Support@cms.hhs.gov

**Comment by gbinal** [comment]
This was discussed but did not come together as a discrete deliverable.
