### ISSUE TITLE
Line up training materials

### ISSUE THREAD

**Issue by gbinal** [18F/CMS.gov-developer#46]
Dependent first on #34

**Comment by mraschka-CMS** [comment]
Audiences:
o   CMS Office of Communications, Web and New Media Group (WNMG)
o   CMS Office of Enterprise Information (OEI)
o   CMS Office of Acquisitions and Grants Management (OAGM)
o   CMS Office of Technology Solutions (OTS)
o   A variety of “business” components

**Comment by gbinal** [comment]
Thanks, @mraschka-CMS.  Next, we should line up dates for these.  We can do any number of trainings, in person or remote, large or small scale.

**Comment by gbinal** [comment]
There appeared not to be interest in doing these at this time, so they were not scheduled.
