### ISSUE TITLE
API Standards

### ISSUE THREAD

**Issue by gbinal** [18F/CMS.gov-developer#5]
https://pages.18f.gov/API-All-the-X/pages/api_standards/

**Comment by nmudd-cms** [comment]
I started working on something that might be a good starting point:
https://github.com/nmudd-cms/wnmg-xlc/blob/master/checklists/api-standards-checklist.md

**Comment by nmudd-cms** [comment]
I think as important we need non-functional requirements that can be acceptance criteria for our stories.
