### ISSUE TITLE
open sourced design elements

### ISSUE THREAD

**Issue by gbinal** [18F/CMS.gov-developer#61]
https://github.com/18F/web-design-standards

**Comment by mbland** [comment]
Note that we _might_ update the [`guides_style_18f` gem](https://github.com/18F/guides-style) with these elements at some point, so https://pages.18f.gov/risk-management-framework/ may get them automatically from there.

**Comment by gbinal** [comment]
https://playbook.cio.gov/designstandards/ is now live.

**Comment by gbinal** [comment]
The goal would be to reconcile ^^^ with http://styleguide.healthcare.gov/.
